apiVersion: batch/v1
kind: Job
metadata:
  name: crep-job
  namespace: kubiya
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: crep
          image: ghcr.io/mitrabeast/crep:latest
          env:
            - name: _EXPERIMENTAL_DAGGER_RUNNER_HOST
              value: tcp://dagger-engine-service:8080
            - name: REG_ADDR
              value: ""
            - name: REG_USER
              value: ""
            - name: REG_PASS
              value: ""
            - name: IMG_NAME
              value: ""
            - name: IMG_TAG
              value: "v5.0"
            - name: USE_DAGGER
              value: "false"
          volumeMounts:
              - name: docker-sock
                mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
